# async/await 如果右边方法执行出错该怎么办？
使用try、catch包裹await，在catch中处理错误